name: Deploy to Fandogh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build And Publish Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: khoonebemoon/khoonebemoon
          tags: latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          dockerfile: Dockerfile
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade fandogh_cli
      - name: Deploy to Fandogh
        env:
          COLLECT_ERROR: false
          F_USERNAME: ${{ secrets.FANDOGH_USERNAME }}
          F_PASSOWRD: ${{ secrets.FANDOGH_PASSWORD }}
        run: |
          fandogh login --username $F_USERNAME --password $F_PASSOWRD
          fandogh service deploy --image khoonebemoon/khoonebemoon --version latest --name "khoone-bemoon" --port 3000 --hosts "khoonebemoon.com" --hosts "www.khoonebemoon.com" --image-pull-policy "Always" -d
